name: Model CI/CD
on: workflow_dispatch

jobs:
  model-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Split Dataset
        run: python src/0-split-dataset.py
      - name: Preprocess Dataset Train
        run: python src/1-preprocess-dataset-train.py
      - name: Prepare Dataset Test
        run: python src/2-prepare-dataset-test.py
      - name: Buil model
        run: echo "Build Model"

  model-cd:
    needs: model-ci
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy Model
        run: echo "Deploy Model"