name: Model CI / CD
on: workflow_dispatch
jobs:
    model-ci:
        runs-on: ubuntu-latest
        steps:
            - name: GET code
              uses: actions/checkout@v4
            - name: Python setup
              uses: actions/setup-python
              with:
                python-version: 3.12
            - name: Install python dependencies
              run: |
               python pip install --upgrade pip
               python pip install -r requirements.txt
            - name: Split Dataset
              run: python scr/0-split-dataset.py